apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: {{ .Values.ingress.host}}
    http:
      paths:
      - path: {{ .Values.ingress.path}}
        backend:
          serviceName: {{ .Values.applicationName }}
          servicePort: {{ .Values.service.externalPort }}