apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.applicationName }}
  ports:
  - protocol: {{ .Values.service.protcol }}
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.deployment.containerPort }}