apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-samuel-braga
  namespace: samuel-braga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-samuel-braga
  template:
    metadata:
      name: game-samuel-braga
      labels:
        app: game-samuel-braga
    spec:
      imagePullSecrets:
      - name: ktk8s-secret
      containers:
      - name: game-samuel-braga
        image: ktk8s.azurecr.io/game-samuelbraga:123
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: "/samuel-braga/index.html"
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 25m
            memory: 128Mi