apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: 2048-samuel-braga
  namespace: samuel-braga
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 2048-samuel-braga
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
