apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: game-samuel-braga
  namespace: samuel-braga
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: game-samuel-braga
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
